### ISSUE TITLE
Switch to SimpleMDE

### ISSUE THREAD

**Issue by duclet** [axllent/silverstripe-gfmarkdown#3]
I think SimpleMDE is probably a better editor to use for this than Ace since it renders the content live too. Thoughts?

**Comment by axllent** [comment]
I think that's a great idea as it's a much nicer editor with cool features! Not sure how well it will play with the SilverStripe admin (ie: fullscreen etc), but worth a shot. I'll have a play and see what I can come up with.

**Comment by axllent** [comment]
OK, this took me a lot longer than expected, and with mixed results. I have managed to integrate it into the CMS fairly easily, however two of SimpleMDE's features (fullscreen & side-by-side editing) don't play nice with the CMS.

Basically the SilverStripe CMS is a series of fixed-positioned divs (eg: main menu, bottom nav, content), and SimpleMDE (in fullscreen/side-by-side editing mode) relies on statically-positioned divs (toolbar, editor/preview, and optionally the side-by-side screen). I started hacking away to find a work-around but decided it was a bad idea, as any changes upstream to the SimpleMDE elements, or any changes to SilverStripe's CMS layout will probably break things. There is also the issue of the main menus in the CMS having two states, collapsed and expanded, and I wasn't able to work out how to detect this, or reliably modify the element sizes in SimpleMDE if/when fullscreen is activated.

I have therefore decided to **hide/disable** the fullscreen & side-by-side editing buttons in the editor. You can still preview the content, just not side-by-side.

Rather than modify this project, I created a new one ([silverstripe-simplemde-markdown](https://github.com/axllent/silverstripe-simplemde-markdown)). Remember to uninstall silverstripe-gfmarkdown when you try it.

Please feel free to contribute if you know a way of getting it to reliably work with the CMS in fullscreen/side-by-side mode!

`composer require axllent/silverstripe-simplemde-markdown`

**Comment by duclet** [comment]
Wow, you are fast. Yeah, I don't use hide/disable either. Thanks.
